import './globals.css'
import localFont from 'next/font/local'
import Nav from "@/components/Nav";

export const TASADisplay = localFont({
    src: [
        {
            path: 'fonts/TASAOrbiterDisplay-Regular.otf',
            weight: '300',
            style: 'normal'
        },
        {
            path: 'fonts/TASAOrbiterDisplay-Medium.otf',
            weight: '500',
            style: 'normal'
        },
        {
            path: 'fonts/TASAOrbiterDisplay-Bold.otf',
            weight: '700',
            style: 'normal'
        },
        {
            path: 'fonts/TASAOrbiterDisplay-Black.otf',
            weight: '900',
            style: 'normal',
        },
    ],
    display: "swap",
    variable: '--font-tasa'
})

export const TASAText = localFont({
    src: [
        {
            path: 'fonts/TASAOrbiterText-Regular.otf',
            weight: '300',
            style: 'normal'
        },
        {
            path: 'fonts/TASAOrbiterText-Medium.otf',
            weight: '500',
            style: 'normal'
        },
        {
            path: 'fonts/TASAOrbiterText-SemiBold.otf',
            weight: '700',
            style: 'normal'
        },
        {
            path: 'fonts/TASAOrbiterText-Bold.otf',
            weight: '900',
            style: 'normal'
        }
    ],
    display: "swap",
    variable: '--font-tasa-text'
})

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({children}) {
    return (
        <html lang="en">
        <body className={`${TASADisplay.variable} ${TASAText.variable}`}>
        <Nav/>
        {children}
        </body>
        </html>
    )
}
